# Generated by Django 4.2.6 on 2023-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(verbose_name='Question object'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pict',
            field=models.ImageField(upload_to='', verbose_name='Your image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='psw',
            field=models.CharField(verbose_name='Password'),
        ),
    ]
