# Generated by Django 4.2.6 on 2023-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='true_answ',
            field=models.BooleanField(default=False),
        ),
    ]
