# Generated by Django 4.2.7 on 2023-11-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_question_rate_questionrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionrate',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionrate',
            old_name='user_id',
            new_name='user',
        ),
    ]
